# Instructs OLM to install the CouchDB operator from the catalog.
# sourceNamespace must match the namespace in catalog-source.yaml.
# For OpenShift, the overlay patches sourceNamespace to 'openshift-marketplace'.
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: couchdb-operator
  namespace: couchdb
spec:
  channel: stable
  name: couchdb-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
