# Scopes the ArgoCD operator to the argocd namespace.
# Must be in the same namespace as the Subscription.
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: argocd-operator-group
  namespace: argocd
spec:
  targetNamespaces:
    - argocd
